40 INPUT "DO YOU WANT INSTRUCTIONS (Y/N)"A$:IF A$="N" THEN 47
41 PRINT "THIS IS THE GAME OF JOTTO. I AM THINKING OF A"
42 PRINT "FIVE LETTER WORD. YOU TRY AND GUESS THE WORD BY"
43 PRINT "PRINTING 5-LETTER WORDS AND I'LL TELL YOU HOW "
44 PRINT "MANY LETTERS IN YOUR WORD ARE IN THE SAME POSITION"
45 PRINT "AS IN MY WORD. YOU GET 15 GUESSES.":PRINT
47 PRINT:PRINT
50 FOR X=1 TO INT(RND(8)*20)+1:READ C$:NEXT
60 RESTORE:T1=0
70 I=1+1:I=1:IF I1=15 THEN 230
75 I=0:Z=1
80 INPUT "YOUR WORD";A$:PRINT:IF LEN(A$)=5 THEN 110
90 IF LEN(A$)>5 THEN PRINT "ONLY 5 LETTERS LONG, PLEASE.":GOTO 80
105 PRINT "NOT";LEN(A$);"LETTERS LONG. FIVE LETTERS LONG!":GOTO 80
108 PRINT "YOU KNOW DAMN WELL THAT WORD DOESN'T EXIST!!":GOTO 75
110 FOR X=1 TO 5
120 IF MID$(A$,X,1)=MID$(A$,X+1,1) THEN Z=Z+1:IF Z=3 THEN 108
130 IF MID$(A$,X,1)=MID$(C$,X,1) THEN T=T+1:IF T=5 THEN 190
150 NEXT
160 IF I=1 THEN PRINT "YOU HAVE 1 LETTER IN THE RIGHT POSITION.":GOTO 70
170 PRINT "YOU HAVE";I;"LETTERS IN THE RIGHT POSITION.":GOTO 70
190 PRINT "YOU GUESSED IT!! AND IN ONLY";I1;"TRIES!!":GOTO 270
230 PRINT "SORRY, TOO MANY GUESSES. THE WORD WAS ";C$
240 DATA INPUT,HELLO,ZEBRA,WHERE,HIVES,START,IRALE,SINKS,SENSE,PRINT
250 DATA DIGIT,APART,DRAMA,START,OPERA,RESET,BASIC,MARCH,COUNT,FAUST
270 INPUT "DO YOU WANT TO TRY AGAIN (Y/N)"A$:IF A$="Y" THEN 47
280 END
